In [8]:
from collections import defaultdict
import os
import pickle
import sys

import numpy as np

from rdkit import Chem


In [5]:
file_path = "../dataset/b_cancer/original/data.txt"

In [7]:
with open(file_path, 'r') as f:
    data_list = f.read().strip().split('\n')

print(data_list[0])

N[C@@H](Cc1ccc(Br)cc1)C(=O)NO MSAIQAAWPSGTECIAKYNFHGTAEQDLPFCKGDVLTIVAVTKDPNWYKAKNKVGREGIIPANYVQKREGVKAGTKLSLMPWFHGKITREQAERLLYPPETGLFLVRESTNYPGDYTLCVSCDGKVEHYRIMYHASKLSIDEEVYFENLMQLVEHYTSDADGLCTRLIKPKVMEGTVAAQDEFYRSGWALNMKELKLLQTIGKGEFGDVMLGDYRGNKVAVKCIKNDATAQAFLAEASVMTQLRHSNLVQLLGVIVEEKGGLYIVTEYMAKGSLVDYLRSRGRSVLGGDCLLKFSLDVCEAMEYLEGNNFVHRDLAARNVLVSEDNVAKVSDFGLTKEASSTQDTGKLPVKWTAPEALREKKFSTKSDVWSFGILLWEIYSFGRVPYPRIPLKDVVPRVEKGYKMDAPDGCPPAVYEVMKNCWHLDAAMRPSFLQLREQLEHIKTHELHL 1


In [9]:
N = len(data_list)

atom_dict = defaultdict(lambda: len(atom_dict))
bond_dict = defaultdict(lambda: len(bond_dict))
fingerprint_dict = defaultdict(lambda: len(fingerprint_dict))
edge_dict = defaultdict(lambda: len(edge_dict))
word_dict = defaultdict(lambda: len(word_dict))

Smiles, compounds, adjacencies, proteins, interactions = '', [], [], [], []


In [11]:
for no, data in enumerate(data_list):

    print('/'.join(map(str, [no+1, N])))

    smiles, sequence, interaction = data.strip().split()

    print(smiles)

"""
    Smiles += smiles + '\n'

    mol = Chem.AddHs(Chem.MolFromSmiles(smiles))  # Consider hydrogens.
    atoms = create_atoms(mol)
    i_jbond_dict = create_ijbonddict(mol)

    fingerprints = extract_fingerprints(atoms, i_jbond_dict, radius)
    print("INNERLOG: fingerprints: ", fingerprints.shape)
    compounds.append(fingerprints)

    adjacency = create_adjacency(mol)
    adjacencies.append(adjacency)

    words = split_sequence(sequence, ngram)
    proteins.append(words)

    interactions.append(np.array([float(interaction)]))
"""

1/2244
N[C@@H](Cc1ccc(Br)cc1)C(=O)NO
2/2244
FC(F)(F)C(=O)c1ccncc1NC(=O)c1ccnc(NC(=O)C2CC2)c1
3/2244
CC(C)(C)OC(=O)Nc1ccc(cc1)-c1cn(CCC[C@H](NC(=O)OCC2c3ccccc3-c3ccccc23)C(O)=O)nn1
4/2244
CC[C@@H](CS(=O)(=O)CC1(C)COC1)N1[C@@H]([C@H](C[C@](C)(CC(O)=O)C1=O)c1cccc(Cl)c1)c1ccc(Cl)cc1
5/2244
COc1ncc(-c2cc3C(=O)N([C@H](c3n2C(C)C)c2ccc(cc2)C#N)c2cc(Cl)cn(C)c2=O)c(OC)n1
6/2244
Cc1nc2N(Cc3cccc(c3)C(F)(F)F)C(=O)CSc2s1
7/2244
COc1ccccc1-c1cc2C(=O)N(C(c2n1C(C)C)c1ccc(Cl)cc1)c1cc(Cl)c(=O)n(C)c1
8/2244
COc1ncc(-c2cc3C(=O)N(C(c3n2C(C)C)c2ccc(Cl)cc2)c2cc(Cl)c(=O)n(C)c2F)c(OC)n1
9/2244
CCC1(CC)N[C@H]([C@H](c2cccc(Cl)c2F)[C@]11C(=O)Nc2cc(Cl)ccc12)C(=O)N[C@H]1CC[C@H](O)CC1
10/2244
CC(C)c1nc2N(C(C)c3cccc(c3)C(F)(F)F)C(=O)CSc2s1
11/2244
Cc1c(ccn2c3C[C@H]4[C@H]([C@H](c5ccnc(Cl)c5F)[C@@]5(N4CC4CC4)C(=O)Nc4cc(Cl)ccc54)c3nc12)C(=O)N1CCCCC1
12/2244
Cc1cncc(NC(=O)c2ccnc(NC(=O)C3CC3)c2)c1
13/2244
CC(C)(C)[C@@H](CS(=O)(=O)N1CCCC1)N1[C@@H]([C@H](C[C@](C)(CC(O)=O)C1=O)c1cccc(Cl)c1)c1ccc(Cl)cc1
14/2244
C1CCN(C1)c1ccc(

'\n    Smiles += smiles + \'\n\'\n\n    mol = Chem.AddHs(Chem.MolFromSmiles(smiles))  # Consider hydrogens.\n    atoms = create_atoms(mol)\n    i_jbond_dict = create_ijbonddict(mol)\n\n    fingerprints = extract_fingerprints(atoms, i_jbond_dict, radius)\n    print("INNERLOG: fingerprints: ", fingerprints.shape)\n    compounds.append(fingerprints)\n\n    adjacency = create_adjacency(mol)\n    adjacencies.append(adjacency)\n\n    words = split_sequence(sequence, ngram)\n    proteins.append(words)\n\n    interactions.append(np.array([float(interaction)]))\n'

In [24]:
compounds_old = np.load("../dataset/human/input/radius2_ngram3/compounds_old.npy", allow_pickle=True)

compounds_old

array([array([17, 18, 19, 20, 21, 22, 23, 24, 24, 23, 25, 26, 27, 28, 29, 30, 31,
              32, 33, 33, 34, 35, 34, 35, 36, 37, 37, 37, 38, 38, 38, 38, 39, 40,
              40, 41, 41, 42, 42, 42, 42, 43, 38, 38, 43, 37, 37, 37, 37, 37, 37,
              44, 44, 44, 44, 44, 44, 45])                                       ,
       array([48, 48, 49, 48, 48, 49, 50, 50, 50, 50, 50, 50, 50, 50]),
       array([17, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 37, 37, 37, 38, 38, 38,
              38, 65, 65, 40, 40])                                               ,
       array([74, 75, 76, 77, 78, 79, 80, 81, 81, 82, 83, 84, 85, 86, 87, 81, 81,
              88, 89, 90, 91, 92, 93, 37, 37, 37, 42, 42, 94, 39, 42, 42, 40, 95,
              95, 42, 42, 38, 38, 50, 50, 44, 44, 44])                           ,
       array([ 33,  99, 100, 101, 102, 103, 104, 105, 106, 103, 104,  37,  37,
               37,  43,  38,  38, 107,  45, 108, 108,  45])                   ,
       array([112, 113, 112,

In [25]:
compounds = np.load("../dataset/human/input/radius2_ngram3/compounds.npy", allow_pickle=True)

compounds

array([array([17, 18, 19, 20, 21, 22, 23, 24, 24, 23, 25, 26, 27, 28, 29, 30, 31,
              32, 33, 33, 34, 35, 34, 35, 36, 37, 37, 37, 38, 38, 38, 38, 39, 40,
              40, 41, 41, 42, 42, 42, 42, 43, 38, 38, 43, 37, 37, 37, 37, 37, 37,
              44, 44, 44, 44, 44, 44, 45])                                       ,
       array([48, 48, 49, 48, 48, 49, 50, 50, 50, 50, 50, 50, 50, 50]),
       array([17, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 37, 37, 37, 38, 38, 38,
              38, 65, 65, 40, 40])                                               ,
       ...,
       array([1028, 3561, 3562,   31, 3563, 3317, 3318,  277, 3319, 3320, 3321,
              3322, 3323,  277, 3324, 3323,  277, 3325,  692, 3326, 3564,   64,
               175,  321, 1020,  378,  697,   36,  994,  601,  601, 1063,   37,
                37,   37,   43,   38,   38,   43,  107,  108,  108,   45,   40,
                40,   40,  380,   45,   45,  399,  399,  399,  399,  399,  399,
                45])  

In [2]:
!pip install pandas

  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.3/11.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.3 MB 1.3 MB/s eta 0:00:09
   -- ------------------------------------- 0.8/11.3 MB 1.3 MB/s eta 0:00:08
   --- ------------------------------------ 1.0/11.3 MB 1.4 MB/s eta 0:00:08
   ----- ---------------------------------- 1.6/11.3 MB 1.4 MB/s eta 0:00:07
   ------ --------------------------------- 1.8/11.3 MB 1.4 MB/s eta 0:00:07
   ------ --------------------------------- 1.8/11.3 MB 1.4 MB/s eta 0:00:07
   ------- -------------------------------- 2.1/11.3 MB 1.3 MB/s eta 0:00:08
   ------- -------------------------------- 2.1/11.3 MB 1.3 MB/s eta 0:00:08
   -------- -----------------------------

In [5]:
#make the graph of the loss over iterations

respath = "../output/result/AUCs--b_cancer--radius2--ngram3--dim10--layer_gnn3--window11--layer_cnn3--layer_output3--lr1e-3--lr_decay0.5--decay_interval10--weight_decay1e-6--iteration100.txt"

import pandas as pd

res = pd.read_csv(respath, delimiter="\t")

res

,Epoch,Time(sec),Loss_train,AUC_dev,AUC_test,Precision_test,Recall_test
0,1,19.470728,829.656900,0.888610,0.771520,0.854545,0.602564
1,2,40.056900,670.824770,0.915789,0.848748,0.670000,0.858974
2,3,61.370864,580.226900,0.923331,0.869048,0.881356,0.666667
3,4,84.042677,528.704830,0.930086,0.884768,0.773333,0.743590
4,5,109.513182,476.064450,0.932600,0.890873,0.789474,0.769231
...,...,...,...,...,...,...,...
94,95,2457.092727,110.565800,0.906520,0.819902,0.695652,0.820513
95,96,2485.770369,110.543460,0.906520,0.819902,0.695652,0.820513
96,97,2512.939756,110.525350,0.906520,0.819902,0.695652,0.820513
97,98,2538.855569,110.511604,0.906520,0.819750,0.695652,0.820513


In [7]:
!pip install matplotlib

  Using cached contourpy-1.3.2-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 621.2 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/8.1 MB 671.3 kB/s eta 0:00:11
   ----- ---------------------------------- 1.0/8.1 MB 774.0 kB/s eta 0:00:10
   ------ --------------------------------- 1.3/8.1 MB 894.7 kB/s eta 0:00:08
   ------- -------------------------------- 1.6/8.1 MB 942.3 kB/s eta 0:00:07
   --------- ------------------------------ 1.8/8.1 MB 986.7 kB/s eta 0:00:07
   ---------- ----------------------------- 2.1/8.1

In [8]:
!pip install seaborn

In [6]:
import matplotlib.pyplot as plt

plt.plot(x=res["Epoch"], y = res["Loss_train"])

ModuleNotFoundError: No module named 'matplotlib'

In [12]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Set Seaborn style for a beautiful look
sns.set_style("whitegrid")
sns.set_context("talk", font_scale=1.2, rc={"font.family": "Helvetica", "lines.linewidth": 2.5})

data = res.copy()
# Data from the provided table
# data = {
#     'Epoch': [0, 1, 2, 3],
#     'Time (sec)': [19.470728, 40.056900, 61.370864, 84.042677],
#     'Loss_train': [829.656900, 670.824770, 580.226900, 528.704830],
#     'AUC_dev': [0.888610, 0.915789, 0.923331, 0.930086],
#     'AUC_test': [0.771520, 0.848748, 0.869048, 0.884768],
#     'Precision_test': [0.854545, 0.670000, 0.881356, 0.773333],
#     'Recall_test': [0.602564, 0.858974, 0.666667, 0.743590]
# }

# Create DataFrame
df = pd.DataFrame(data)

# Create figure and axis objects with a secondary y-axis
fig, ax1 = plt.subplots(figsize=(12, 7))

# Define a vibrant color palette
colors = sns.color_palette("husl", 5)  # 5 colors for the 5 metrics

# Plot performance metrics on primary y-axis
ax1.plot(df['Epoch'], df['Loss_train'], marker='o', label='Loss (Train)', color=colors[0], markersize=10)
# ax1.plot(df['Epoch'], df['AUC_dev'] * 1000, marker='s', label='AUC (Dev) × 1000', color=colors[1], markersize=10)
# ax1.plot(df['Epoch'], df['AUC_test'] * 1000, marker='^', label='AUC (Test) × 1000', color=colors[2], markersize=10)
# ax1.plot(df['Epoch'], df['Precision_test'] * 1000, marker='d', label='Precision (Test) × 1000', color=colors[3], markersize=10)
# ax1.plot(df['Epoch'], df['Recall_test'] * 1000, marker='*', label='Recall (Test) × 1000', color=colors[4], markersize=10)

# Set labels and title for primary y-axis
ax1.set_xlabel('Epoch', fontsize=14, weight='bold')
ax1.set_ylabel('Loss', fontsize=14, weight='bold')
# ax1.set_title('Performance Metrics Over Epochs for QEFS', fontsize=16, weight='bold', pad=20)

# Create secondary y-axis for Time
# ax2 = ax1.twinx()
# ax2.plot(df['Epoch'], df['Time(sec)'], marker='x', label='Time (sec)', color='teal', linestyle='--', markersize=10)
# ax2.set_ylabel('Time (sec)', fontsize=14, weight='bold', color='teal')
# ax2.tick_params(axis='y', labelcolor='teal')

# Combine legends from both axes
# lines1, labels1 = ax1.get_legend_handles_labels()
# lines2, labels2 = ax2.get_legend_handles_labels()
# ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper center', bbox_to_anchor=(0.5, -0.15), ncol=3, fontsize=10, frameon=True, edgecolor='black')

# Adjust layout to prevent overlap
plt.tight_layout()

# Save the plot as a high-resolution PNG
plt.savefig('metrics_plot_seaborn.png', dpi=300, bbox_inches='tight')
plt.close()